### ISSUE TITLE
relocate on maxwidth ?

### ISSUE THREAD

**Issue by raphaelgoetter** [edenspiekermann/minwidth-relocate#1]
Hello,

For compatibilities issues on desktop, I need to detect max-width instead of min-width.
Is it possible to have the choice in a further version of relocate ?

I tried to modify the minified JS but didn't suceed. Do you know where to change the code ?

Thank you

**Comment by mottihoresh** [comment]
I think if you pass a fourth parameter of true to the relocate method it would. 

correction: thats the case in the minwidth method, not sure about the relocate function

**Comment by raphaelgoetter** [comment]
something like relocate(480, nav, main, true); ?

**Comment by raphaelgoetter** [comment]
I tried 

function relocate(480, nav, main) {
      minwidth(480, null, enhanceMobile, true);
    }

but doesn't work.

**Comment by mottihoresh** [comment]
Hi Raphael,

You can try my modification to the code at: https://github.com/mottihoresh/minwidth-relocate

I've updated the relocate function to accept a fourth parameter, so you could do
relocate(1000, elements, destination, true);
               |
               |
           Max Width

The elements would move if the page width is less then the maxwidth

**Comment by raphaelgoetter** [comment]
Great, thank you !
I'll try it as soon as possible this week-end

**Comment by raphaelgoetter** [comment]
Well, I tried on this page : http://www.thinkmobilefirst.net/content/8.html
But doesn't seem to work :/

**Comment by mottihoresh** [comment]
It seems like that your script file doesn't have the right stuff in it.

**Comment by raphaelgoetter** [comment]
Yes it wasn't the right file. It works now, thank you :)

**Comment by eikes** [comment]
The fourth argument has been added to the relocate function as well, see here: https://github.com/edenspiekermann/minwidth-relocate/pull/2

Thanks for the feedback!
